const Constants = {
  SWITCH_TAB: 'SWITCH_TAB',
  LOAD_TEAMS: 'LOAD_TEAMS',
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_USERS: 'LOAD_USERS',
  LOAD_BOARDS: 'LOAD_BOARDS',
  LOAD_LANES: 'LOAD_LANES',
  CHANGE_TEAM: 'CHANGE_TEAM',
  CHANGE_TASK: 'CHANGE_TASK',
  CHANGE_USER: 'CHANGE_USER',
  CHANGE_BOARD: 'CHANGE_BOARD',
  CHANGE_LANE: 'CHANGE_LANE',
};
export default Constants;
